# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("messages.proto", :syntax => :proto3) do
    add_message "ruby_tracker.tracking.User" do
      optional :stranger_id, :string, 1
      proto3_optional :external_id, :string, 2
      proto3_optional :email, :string, 3
    end
    add_message "ruby_tracker.tracking.Navigator" do
      optional :app_code_name, :string, 1
      optional :app_name, :string, 2
      optional :app_version, :string, 3
      optional :cookie_enabled, :bool, 4
      optional :language, :string, 5
      optional :platform, :string, 6
      optional :product, :string, 7
      optional :product_sub, :string, 8
      optional :vendor, :string, 9
      optional :vendor_sub, :string, 10
    end
    add_message "ruby_tracker.tracking.BrowserClient" do
      optional :user_agent, :string, 1
      optional :navigator, :message, 2, "ruby_tracker.tracking.Navigator"
    end
    add_message "ruby_tracker.tracking.NativeClient" do
      optional :os, :string, 1
      optional :os_version, :string, 2
      optional :platform, :string, 3
    end
    add_message "ruby_tracker.tracking.ServerClient" do
      optional :os, :string, 1
      optional :os_version, :string, 2
      optional :framework, :string, 3
    end
    add_message "ruby_tracker.tracking.Client" do
      optional :id, :string, 1
      oneof :implementation do
        optional :browser, :message, 2, "ruby_tracker.tracking.BrowserClient"
        optional :native, :message, 3, "ruby_tracker.tracking.NativeClient"
        optional :server, :message, 4, "ruby_tracker.tracking.ServerClient"
      end
    end
    add_message "ruby_tracker.tracking.Property" do
      optional :name, :string, 1
      optional :value, :string, 2
    end
    add_message "ruby_tracker.tracking.Event" do
      optional :name, :string, 1
      optional :user, :message, 2, "ruby_tracker.tracking.User"
      optional :client, :message, 3, "ruby_tracker.tracking.Client"
      optional :sent_at, :message, 4, "google.protobuf.Timestamp"
      repeated :properties, :message, 5, "ruby_tracker.tracking.Property"
    end
    add_message "ruby_tracker.tracking.EventResponse" do
      optional :session_id, :string, 1
      optional :status, :int32, 2
      proto3_optional :message, :string, 3
    end
  end
end

module RubyTracker
  module Tracking
    User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_tracker.tracking.User").msgclass
    Navigator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_tracker.tracking.Navigator").msgclass
    BrowserClient = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_tracker.tracking.BrowserClient").msgclass
    NativeClient = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_tracker.tracking.NativeClient").msgclass
    ServerClient = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_tracker.tracking.ServerClient").msgclass
    Client = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_tracker.tracking.Client").msgclass
    Property = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_tracker.tracking.Property").msgclass
    Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_tracker.tracking.Event").msgclass
    EventResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_tracker.tracking.EventResponse").msgclass
  end
end
