# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracking_service.proto

require 'google/protobuf'

require 'messages_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tracking_service.proto", :syntax => :proto3) do
  end
end

module RubyTracker
  module Tracking
  end
end
