# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tracking_service.proto for package 'ruby_tracker.tracking'

require 'grpc'
require 'tracking_service_pb'

module RubyTracker
  module Tracking
    module Tracking
      # Basic tracking service
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'ruby_tracker.tracking.Tracking'

        # Receives a stream of events sent by clients, returning an EventResponse
        # when the stream ends
        rpc :CreateEvent, stream(::RubyTracker::Tracking::Event), ::RubyTracker::Tracking::EventResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
